batch_size: 4
num_epochs: 2
num_workers: 2
scales: [1]

data_root: '/home/ubuntu/projects/datasets/synthrel1'
path: 'scene_info.json'

method: 'supervised'
lr: 0.1
cuda: True

GPN:
  N_heads: 2
  feat_in: 128

logs:
  loss_out: 8

writer:
  use_writer: True
