batch_size: 4
num_epochs: 60
num_workers: 4
scales: [1]

data_root: '/Users/i517610/PycharmProjects/SynRelDetection/datasets/sr3/'
path: 'scene_info.json'

method: 'supervised'
lr: 0.001
cuda: False

FeatNet:
  feat_out: 64

GPN:
  N_heads: 2
  feat_in: 64

logs:
  loss_out: 20
  val: 80

writer:
  use_writer: True
