batch_size: 4
num_epochs: 150
num_workers: 4
scales: [1]

data_root: '/Users/i517610/PycharmProjects/SynRelDetection/datasets/sr4/'
path: 'scene_info.json'

train:
  method: 'unsupervised'
  lr: 0.0001
  cuda: False
  schedule:
    lr_step_every: 20
    gamma: 0.5

FeatNet:
  feat_out: 64

GPN:
  N_heads: 2
  feat_in: 64
  net_mode: 'simple'

FP:
  n_transforms: 2

logs:
  loss_out: 50
  im_out: 100
  val: 2

writer:
  use_writer: True

limiter:
  fraction_dropped: 0.0
